configfile: "config/config.yaml"

PERMUTATIONS = {
    "landscape": config["landscapes"],
    "topography": config["topographies"],
    "landclass": config["landclasses"]
}
carbon_stocks = expand("results/carbon_stocks/{landscape}/{topography}.{landclass}.LandscapeCarbonStock.tif", **PERMUTATIONS)
greenhouse_gas_emissions = expand("results/greenhouse_gas_emissions/{landscape}/{topography}.{landclass}.LandscapeGreenhouseGasEmissions.tif", **PERMUTATIONS)
pollinator_overlap = expand("results/pollination/{landscape}/{topography}.{landclass}.LandscapePollinatorOverlap.tif", **PERMUTATIONS)

include: "rules/pollination.smk"
include: "rules/carbon.smk"
include: "rules/ghg.smk"

rule all:
    input:
        carbon_stocks,
        greenhouse_gas_emissions,
        pollinator_overlap
