topographies:
  - t0
  - t1
  - t2
  - t3
  - t4
  - t5
  - t6
  - t7
  - t8
  - t9

landclasses:
  - c5
  - c10
  - c50
  - c100
  - c500
  - c1000

proportions:
  - p0
  - p1
  - p2
  - p3

landscapes:
  - hills
  - mountains
  - plains

basepath: "/cifs/Tlinc/Projects K-O/MCSL/virtual-landscapes-50km"

# height and width of a pixel, in metres
RESOLUTION: 25
# Height and width of the entire region, in pixels
WIDTH: 2000
HEIGHT: 2000
